version: '3.8'

services:
  mysql:
    image: mysql:8.0.40-debian
    environment:
      MYSQL_ROOT_PASSWORD: sawa
      MYSQL_DATABASE: mtrack
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./MySQL-Workbench-Queries/init.sql:/docker-entrypoint-initdb.d/init.sql

  flask-app:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app/flask/
    
    command: >
      sh -c "
      pip install flask requests mysql-connector-python &&
      python --version &&
      python routes.py
      "
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
