version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: sawa
      POSTGRES_PASSWORD: sawa
      POSTGRES_DB: mtrack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./MySQL-Workbench-Queries/init.sql:/docker-entrypoint-initdb.d/init.sql


  flask-app:
    image: python:3.10
    volumes:
      - .:/app
    working_dir: /app/flask/
    command: >
      sh -c "
      pip install flask requests psycopg2 &&
      python --version &&
      python routes.py
      "
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local
